const data = {
    products: [
        {
            name: 'Free Shirt',
            category: 'Shirts',
            image: '/images/shirt1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Fit Shirt',
            category: 'Shirts',
            image: '/images/shirt2.jpg',
            price: 70,
            brand: 'Adidas',
            rating: 4.2,
            numReviews: 10,
            countInStock: 20,
            description: 'A gym shirt',
        },
        {
            name: 'Slim Shirt',
            category: 'Shirts',
            image: '/images/shirt3.jpg',
            price: 70,
            brand: 'Stone Island',
            rating: 4.9,
            numReviews: 1,
            countInStock: 20,
            description: 'A clean looking shirt',
        },
        {
            name: 'Gym Shirt',
            category: 'Shirts',
            image: '/images/shirt1.jpg',
            price: 20,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A dry-fit shirt',
        },
        {
            name: 'Free Pant',
            category: 'Pants',
            image: '/images/pants1.jpg',
            price: 170,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular pant',
        },
        {
            name: 'Fit Pant',
            category: 'Pants',
            image: '/images/pants2.jpg',
            price: 40,
            brand: 'Gucci',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A fit pant',
        },
    ],
};
export default data;